//favorites
export const GET_FAVORITES_REQUESTED = 'GET_FAVORITES_REQUESTED';
export const GET_FAVORITES_SUCCEEDED = 'GET_FAVORITES_SUCCEEDED';
export const GET_FAVORITES_FAILED = 'GET_FAVORITES_FAILED';

export const DELETE_FAVORITES_REQUESTED = 'DELETE_FAVORITES_REQUESTED';
export const DELETE_FAVORITES_SUCCEEDED = 'DELETE_FAVORITES_SUCCEEDED';
export const DELETE_FAVORITES_FAILED = 'DELETE_FAVORITES_FAILED';

//random image
export const GET_RANDOM_REQUESTED = 'GET_RANDOM_REQUESTED';
export const GET_RANDOM_SUCCEEDED = 'GET_RANDOM_SUCCEEDED';
export const GET_RANDOM_FAILED = 'GET_RANDOM_FAILED';

export const SET_FAV_RANDOM_REQUESTED = 'SET_FAV_RANDOM_REQUESTED';
export const SET_FAV_RANDOM_SUCCEEDED = 'SET_FAV_RANDOM_SUCCEEDED';
export const SET_FAV_RANDOM_FAILED = 'SET_FAV_RANDOM_FAILED';

export const DELETE_FAV_RANDOM_SUCCEEDED = 'DELETE_FAV_SUCCEEDED';

//position
export const INCREMENT_POSITION = 'INCREMENT_POSITION';
export const DECREMENT_POSITION = 'DECREMENT_POSITION';
export const SET_POSITION = 'SET_POSITION';

//isLoading
export const SET_LOADING = 'SET_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';
