//favorites
export const GET_FAVORITES_REQUESTED ='GET_FAVORITES_REQUESTED';
export const GET_FAVORITES_SUCCEEDED ='GET_FAVORITES_SUCCEEDED';
export const GET_FAVORITES_FAILED='GET_FAVORITES_FAILED';

export const DELETE_FAVORITES_REQUESTED ='DELETE_FAVORITES_REQUESTED';
export const DELETE_FAVORITES_SUCCEEDED ='DELETE_FAVORITES_SUCCEEDED';
export const DELETE_FAVORITES_FAILED ='DELETE_FAVORITES_FAILED';